FROM node:14-alpine AS build

WORKDIR /app

COPY . .

RUN yarn install

RUN yarn build

#EXPOSE 3000

#CMD ["yarn","start"]

FROM nginx

EXPOSE 80

COPY --from=build /app/build/. /usr/share/nginx/html/

CMD ["nginx","-g","daemon off;"]




