
FROM maven:3.9.6-eclipse-temurin-11-focal AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

#ENV PORT 7000
#ENV ACTIVE_PROFILE dev
#ENV DB_HOST dbb
#ENV DB_PORT 3306
#ENV DB_SCHEMA ecommerce_app_database
#ENV DB_USER mysqluser
#ENV DB_PASS mypass

RUN mvn package -DskipTests


FROM openjdk:11-ea-jre

ENV PORT 7000
ENV ACTIVE_PROFILE dev
ENV DB_HOST bdd
ENV DB_PORT 3306
ENV DB_SCHEMA ecommerce_app_database
ENV DB_USER mysqluser
ENV DB_PASS mypass

WORKDIR /app

COPY --from=builder /app/target/authentication-service.jar .

EXPOSE 7000

ENTRYPOINT ["java","-jar","authentication-service.jar"]

